AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames:
    - x
    - y

Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/MultilineBlockChain:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - "*.gemspec"

Metrics/ParameterLists:
  Max: 6

Metrics/AbcSize:
  Max: 66

Metrics/ClassLength:
  Max: 258

Metrics/CyclomaticComplexity:
  Max: 14

Metrics/MethodLength:
  Max: 52

Metrics/ModuleLength:
  Exclude:
    - spec/**/*
  Max: 602

Metrics/PerceivedComplexity:
  Max: 14

