inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - "*.gemspec"

Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames:
    - x
    - y

Naming/FileName:
  Exclude:
    - 'gemfiles/*.gemfile'

Style/MultilineBlockChain:
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Exclude:
    - spec/**/*

Metrics/ParameterLists:
  Max: 6
