inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - "*.gemspec"

Naming/MethodParameterName:
  AllowedNames:
    - x
    - y
    - id
    - to
    - on

Naming/FileName:
  Exclude:
    - 'gemfiles/websocket-driver-*.gemfile'
