addons:
  chrome: stable
gemfile:
  - gemfiles/websocket-driver-0.6.x.gemfile
  - gemfiles/websocket-driver-0.7.x.gemfile
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.2.8.0
matrix:
  allow_failures:
  - rvm: jruby-9.2.8.0
